# Generated by Django 5.2.5 on 2025-08-12 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BarberShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='Experiência premium em cortes e barbas. Tradição, qualidade e estilo em cada atendimento. Agende online e viva uma nova experiência.', null=True)),
                ('open_since', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=100)),
                ('coordenation', models.CharField(max_length=100)),
            ],
        ),
    ]
