# Generated by Django 5.2.5 on 2025-08-12 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='address',
            field=models.CharField(default='Duque de Caxias', max_length=200),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='coordenation',
            field=models.CharField(default='-22.787954, -43.310263', max_length=100),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='description',
            field=models.TextField(blank=True, default='Experiência em cortes e barbas. Tradição, qualidade e estilo em cada atendimento. Agende online e viva uma nova experiência.', null=True),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='name',
            field=models.CharField(default='Max Barber', max_length=100),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='open_since',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AlterField(
            model_name='barbershop',
            name='phone',
            field=models.CharField(default='21987825934', max_length=100),
        ),
    ]
