services:
  web:
    build: .
    container_name: django
    ports:
      - "8000:8000"
    volumes:
      - .:/core
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
