# Generated by Django 5.2.5 on 2025-08-06 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0002_barber_services'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('reason', models.CharField(blank=True, max_length=100, null=True)),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_times', to='barbers.barber')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(0, 'Seg'), (1, 'Ter'), (2, 'Qua'), (3, 'Qui'), (4, 'Sex'), (5, 'Sab'), (6, 'Dom')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('barber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_hours', to='barbers.barber')),
            ],
        ),
    ]
