# Generated by Django 5.2.5 on 2025-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers', '0003_blockedtime_workinghour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barber',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/'),
        ),
    ]
