# Generated by Django 5.2.5 on 2025-08-12 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_service_is_popular'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_original', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('duration_days', models.PositiveIntegerField(default=30)),
                ('is_popular', models.BooleanField(default=False)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('card_color', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlanBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('allowed_days', models.JSONField(blank=True, default=list)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='plans.plan')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
