# Generated by Django 5.2.5 on 2025-08-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
    ]
