# Generated by Django 5.2.5 on 2025-08-07 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Dono(a)'), ('client', 'Cliente'), ('barber', 'Barbeiro(a)')], default='client', max_length=20),
        ),
    ]
