# Generated by Django 5.2.5 on 2025-08-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancel_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='canceled_by',
            field=models.CharField(blank=True, choices=[('admin', 'Dono(a)'), ('client', 'Cliente'), ('barber', 'Barbeiro(a)')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pendent', 'Pendente'), ('scheduled', 'Agendado'), ('completed', 'Concluído'), ('canceled', 'Cancelado'), ('no_show', 'Não compareceu')], default='pendent', max_length=20),
        ),
    ]
