# Generated by Django 5.2.5 on 2025-08-12 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_appointment_cancel_reason_appointment_canceled_at_and_more'),
        ('plans', '0002_remove_plan_price_original_plansubscription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='paid_with_plan',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointment',
            name='plan_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='plans.plansubscription'),
        ),
    ]
